Ds pundit
dylansarikas/industrial-auth-1 pull request #2
Opened 2024-07-17 18:13 UTC by dylansarikas

pull request for pundit

2024-07-17 21:04 UTC, SaraDawner2000 approved these changes
Looks good!
Maybe some cleanup can be done after we removed many of the automatically generated with scaffold routes

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/controllers/comments_controller.rb
>    before_action :is_an_authorized_user, only: [:destroy, :create]
Do you still need this before action?

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/controllers/comments_controller.rb
> +  before_action :authorize_comment, only: [:show, :edit, :update, :destroy]
Same as above

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/controllers/follow_requests_controller.rb
>    before_action :set_follow_request, only: %i[ show edit update destroy ]
same as above

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/controllers/follow_requests_controller.rb
> +  before_action :authorize_follow_request, only: [:show, :edit, :update, :destroy]
same as above

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/policies/application_policy.rb
Do you use these policies?

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/policies/user_policy.rb
> +  def feed?
Should this be accessible to users that aren't the current user?

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/policies/user_policy.rb
> +  def discover?
Same as above

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/policies/follow_request_policy.rb
> +  def update?
Can the recipient of the follow request update it?

2024-07-17 21:04 UTC, SaraDawner2000 commented on app/views/users/show.html.erb
> +<% if policy(@user).show_photos? %>
smart making a separate policy!

2024-07-18 14:06 UTC, dylansarikas commented on app/policies/follow_request_policy.rb
> +  def update?
yes

2024-07-18 19:45 UTC, ajmompr requested changes

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  include Pundit::Authorization
This is okay! You can also just list "include Pundit"

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, except: :index, unless: :devise_controller?
good job accounting for Devise

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?
good job accounting for Devise

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +    authorize @comment
This is fine! You can also refactor to before_action -> { authorize @comment || Comment }, except: [:new, :create]

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +  before_action :authorize_follow_request, only: [:show, :edit, :update, :destroy]
can be refactored to add before_action { authorize @follow_request || FollowRequest}. This way, you do not need to add the authorize @follow_request method to each individual action

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +    authorize @follow_request
same as above. This is okay; however, we can refactor make the code more DRY

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +    authorize @follow_request
same as above. This is okay; however, we can refactor make the code more DRY

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +      authorize @follow_request
same as above. This is okay; however, we can refactor make the code more DRY

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action :authorize_photo, only: [:show, :edit, :update, :destroy]
Similar to your FollowRequestsController; can be refactored to add before_action { authorize ...}. This way, you do not need to add the authorize @photo to each individual action

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
same as above; can make this more DRY

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
same as above; can make this more DRY

2024-07-18 19:45 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  before_action :authorize_user
similar to previous controllers! Can refactor

2024-07-18 19:45 UTC, ajmompr commented on app/policies/application_policy.rb
> +class ApplicationPolicy
good use of pundit generator

2024-07-18 19:45 UTC, ajmompr commented on app/policies/comment_policy.rb
> +  def new?
can make this more DRY. For example, you can use inheritance. If the new? permissions are the same as show?.  This can be re-written as 
```ruby
def new? 
show?
end```

2024-07-18 19:45 UTC, ajmompr commented on app/policies/comment_policy.rb
> +    user == comment.author
can make more DRY

2024-07-18 19:45 UTC, ajmompr commented on app/policies/comment_policy.rb
> +    user == comment.author
same as above

2024-07-18 19:45 UTC, ajmompr commented on app/policies/follow_request_policy.rb
> +    user = follow_request.sender
can be more DRY

2024-07-18 19:45 UTC, ajmompr commented on app/policies/photo_policy.rb
> +    user == photo.owner
can be more DRY

2024-07-18 19:45 UTC, ajmompr commented on app/policies/user_policy.rb
> +  def feed?
+1

2024-07-18 19:45 UTC, ajmompr commented on app/views/users/show.html.erb
> +<% if policy(@user).show_photos? %>
+1

2024-07-18 20:12 UTC, dylansarikas commented on app/controllers/application_controller.rb
> +  include Pundit::Authorization
per the documentation, include Pundit is depreciated

2024-07-22 01:56 UTC, ajmompr approved these changes
perfect! good job

2024-07-22 01:56 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +  before_action -> { authorize @comment || Comment },except: [:new, :create]
good

2024-07-22 01:56 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +    authorize @comment
if you are using the before action, this line is redundant

2024-07-22 01:56 UTC, ajmompr commented on app/controllers/follow_requests_controller.rb
> +  before_action { authorize @follow_request || FollowRequest }
good

2024-07-22 01:56 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action { authorize @photo || Photo }
good

2024-07-22 01:56 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  before_action { authorize @user || User }
good

2024-07-22 02:36 UTC, merged